project:
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "Daniel Thuv Eriksen"
  chapters:
    - index.qmd
    - Rapport-1-Eksamen.qmd
    - Rapport 2-Eksamen.qmd
    - Rapport-3-Eksamen.qmd
    - Rapport-4-Studiedesign.qmd
    - Rapport-5-Eksamen-NY.qmd
    - Filosofihistorie-Eksamen.qmd
    - Labrapport-Eksamen.qmd
    

format: pdf