---
bibliography: references.bib
---

## Introduksjon

**Mappeeksamen består av følgende deler:**

-   Rapport 1: “Deskriptiv statistikk, reliabilitet og validitet og verktøy for reproduserbar vitenskap”.

-   Rapport 2: "Predikere data ved hjelp av regresjon"

-   Rapport 3: “Statistisk inferens, statistiske modeller og statistisk styrke”

-   Rapport 4: “Studiedesign”

-   Rapport 5: “Analyse av eksperimenter med repeterte målinger"

-   Arbeidskrav i filosofihistorie

-   Laboratorierapport fra molekylærlabb

## Forord

Jeg vil gjerne takke Lone, Lars og Ulrich for et godt samarbeid på Rapport 1/2 og labratorierapporten. I tillegg vil jeg takke Jens Konrad Daniel Hammarström for hjelp på veien når kodene har vært kranglete. Denne oppgaven ville ikke vært mulig uten de som er nevnt. Under ligger lenken til Mappeeksamen sin repository på GitHub med alle kodene som har blitt benyttet til å besvare de ulike delene av eksamen.

Lenke til repository: <https://github.com/DanielTEriksen/Mappeeksamen>
